name: Copy repo README to library

on:
  push:
    branches: [main]

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy README to library
        run: |
          cp README.md projects/console-forge/README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add projects/console-forge/README.md
          git commit -m "Overwrite library README with repo README" || echo "No changes"
          git push
